Complete redesign of the nanotrasen.se webpage.
ParadiseSS13/nanotrasen.se pull request #3
Opened 2016-12-16 20:42 UTC by Draconic-saint

Still small things that need to be fixed.

- I added in the patreon banner but I didn't end up use it. It does seem like this might be a thing future devs might want to use, who knows, let me know if I got to axe it, no problem.

- I have no idea about licences or legal stuff that's required to go into the footer, so for now it's placeholder text.

- I might update the background soon to give it a more space vibe, in place of the now 100% abstract look I got going now.

2016-12-17 15:48 UTC, Regen1 requested changes
Only other thing that needs changing is perhaps the text, we need to finalize it and clear it with Freestyle

2016-12-17 15:48 UTC, Regen1 commented on index.css
> +    color: whitesmoke;
User hex or rbg

2016-12-17 15:48 UTC, Regen1 commented on index.css
> +    color: white;
#ffffff

2016-12-17 15:48 UTC, Regen1 commented on index.css
> +    color: darkgray;
Hex for color

2016-12-17 15:48 UTC, Regen1 commented on index.css
> +    color: whitesmoke;
Hex

2016-12-17 15:48 UTC, Regen1 commented on index.php
> +           <li id ="logo"><a  href="index.html"><img src="Images/Paradise2icon.PNG" alt="server logo"></a></li>
Formatting, not on the same line as everything else

2016-12-17 15:48 UTC, Regen1 commented on index.php
> +   <footer><p>Licences, copyright and other guff like icons for patreon/discord/git goes here.</p></footer>
Should add something about the MIT license here

2016-12-17 15:55 UTC, FreeStylaLT commented on index.php
> +                We like to pride ourselves that the general playstyle on our server is a healthy mix or RP & action. So join us on the cyberiad, and try to stay alive, atleast for a while.
We like to pride ourselves that the general playstyle on our server is a healthy mix of RP & Action. Come join us on the Cyberiad, and try to stay alive, at least for a while.

2016-12-17 15:56 UTC, FreeStylaLT commented on index.php
> +                   <p>Throughout the years, we've built a solid community around our server, with an active forum and a public discord server.</p> <p> The <a href="https://nanotrasen.se/phpBB3/">foru
Throughout the years, we've built a solid community around our server, with an active forum and a public discord server.</p> <p> The <a href="https://nanotrasen.se/phpBB3/">forums</a> are our official discussion space, where everything can be documented easily, while the <a href="https://discord.gg/nuqD478">discord</a> is a more informal space where players and admins alike can hang out and chat.</p>

2016-12-17 15:58 UTC, FreeStylaLT commented on index.php
> +                   <p>Running a server costs money sadly. Previously we accepted donations to keep that server running. Now we've set up a patreon for that purpose. It also allows us to give thanks t
Sadly, running a server is not free. Previously we accepted donations to keep that server running. Now we've set up a Patreon for that purpose. It also allows us to provide various cosmetic bonuses as a way of thanking our patrons.</p><p>You can find out more about the patron tiers on our <a href="https://www.patreon.com/ParadiseStation">Patreon</a> page!

2016-12-17 16:10 UTC, tigercat2000 commented on index.php
> +                   <p>Throughout the years, we've built a solid community around our server, with an active forum and a public discord server.</p> <p> The <a href="https://nanotrasen.se/phpBB3/">foru
Please make this multi-line as well, it's difficult to change it as-is.

2016-12-17 16:18 UTC, Draconic-saint commented on index.php
> +                   <p>Throughout the years, we've built a solid community around our server, with an active forum and a public discord server.</p> <p> The <a href="https://nanotrasen.se/phpBB3/">foru
Seperate lines for the discord and the forum links?

2016-12-17 23:07 UTC, tigercat2000 commented on index.php
> +                   <p>Throughout the years, we've built a solid community around our server, with an active forum and a public discord server.</p> <p> The <a href="https://nanotrasen.se/phpBB3/">foru
@Draconic-saint It's HTML, and you're using <p> tags anyways, newlines won't have any effect on the final product (I think)

2016-12-18 21:06 UTC, Regen1 approved these changes

2016-12-29 18:04 UTC, merged